# 🤖 Claude Auto-Fix Configuration
# Configuration file for Claude Auto-Fix behavior

# Safety Settings
safety:
  # Conservative mode - only fix obvious errors
  conservative_mode: true
  
  # Maximum number of files to modify in single PR
  max_files_per_fix: 10
  
  # Maximum lines of code to change in single file
  max_lines_per_file: 50
  
  # Require manual review for these file types
  protected_files:
    - "*.sql"
    - "database/migrations/*"
    - "config/*.php"
    - ".env*"
    - "composer.json"
    - "package.json"
  
  # Never modify these directories
  forbidden_paths:
    - "vendor/"
    - "node_modules/"
    - "storage/"
    - ".git/"
    - "public/build/"

# Error Detection Settings
error_detection:
  # Types of errors to detect and fix
  enabled_detectors:
    - "php_syntax_errors"
    - "test_failures"
    - "phpstan_issues" 
    - "phpcs_violations"
    - "composer_validation"
    - "missing_imports"
  
  # Severity levels to address
  min_severity: "error"  # error, warning, notice
  
  # Maximum number of errors to fix in single run
  max_errors_per_run: 5

# Claude AI Settings
claude:
  # Model to use for fixes
  model: "claude-3-sonnet-20240229"
  
  # Maximum tokens for Claude response
  max_tokens: 4000
  
  # Temperature for Claude responses (0.0 = deterministic, 1.0 = creative)
  temperature: 0.1
  
  # Custom instructions for Claude
  custom_instructions: |
    You are a senior PHP/Laravel developer with expertise in healthcare systems.
    Focus on maintaining HIPAA compliance and data security.
    Always preserve existing business logic and database integrity.
    Be extremely conservative with changes to patient data handling.

# Pull Request Settings  
pull_request:
  # Auto-assign reviewers
  auto_assign_reviewers: true
  
  # Reviewers to assign (GitHub usernames)
  default_reviewers:
    - "admin"
    - "lead-developer"
  
  # Labels to add to auto-fix PRs
  labels:
    - "🤖 auto-fix"
    - "🔧 bug-fix"
    - "🧪 needs-testing"
    - "📋 needs-review"
  
  # Branch naming pattern
  branch_prefix: "claude-auto-fix"
  
  # Auto-merge settings
  auto_merge:
    enabled: false  # Never auto-merge, always require review
    require_passing_tests: true
    require_reviews: 2

# Monitoring & Logging
monitoring:
  # Log all Claude interactions
  log_claude_requests: true
  
  # Send notifications on fix attempts
  notifications:
    slack_webhook: ""  # Add Slack webhook URL if desired
    email_alerts: []   # Add email addresses for alerts
  
  # Rate limiting
  rate_limiting:
    max_requests_per_hour: 10
    max_requests_per_day: 50

# Testing Settings
testing:
  # Run these test commands after applying fixes
  test_commands:
    - "php artisan test --stop-on-failure"
    - "vendor/bin/phpstan analyse --no-progress"
    - "vendor/bin/phpcs --standard=PSR12 app/"
  
  # Test timeout in seconds
  timeout: 300
  
  # Fail fix if tests don't pass
  require_passing_tests: true

# Rollback Settings
rollback:
  # Enable automatic rollback on failure
  auto_rollback: true
  
  # Keep fix attempts for analysis
  keep_failed_branches: true
  
  # Maximum number of fix attempts before giving up
  max_attempts: 3

# Specific Fix Rules
fix_rules:
  # PHP-specific rules
  php:
    # Always add strict types declaration
    add_strict_types: false
    
    # Fix PSR-12 violations
    fix_code_style: true
    
    # Add missing return types
    add_return_types: false  # Too risky for auto-fix
    
    # Fix missing imports
    fix_missing_imports: true
  
  # Laravel-specific rules
  laravel:
    # Fix model relationships
    fix_relationships: false  # Too complex for auto-fix
    
    # Fix validation rules
    fix_validation: false     # Business logic sensitive
    
    # Fix route definitions
    fix_routes: false         # Security sensitive
    
    # Fix database queries
    fix_queries: true         # Only obvious syntax issues
  
  # Testing rules
  testing:
    # Fix assertion methods
    fix_assertions: true
    
    # Add missing test annotations
    add_annotations: false
    
    # Fix test data factories
    fix_factories: true

# Emergency Settings
emergency:
  # Disable auto-fix completely
  disabled: false
  
  # Emergency contacts
  contacts:
    - "admin@dokterku.com"
    - "developer@dokterku.com"
  
  # Circuit breaker - disable after N consecutive failures
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    reset_timeout: 3600  # 1 hour

# Reporting
reporting:
  # Generate fix reports
  generate_reports: true
  
  # Report format
  format: "markdown"  # markdown, json, html
  
  # Include metrics
  include_metrics: true
  
  # Metrics to track
  metrics:
    - "fix_success_rate"
    - "test_pass_rate"
    - "files_modified"
    - "lines_changed"
    - "time_to_fix"