name: Build
  on: [push]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
        - run: composer install --ignore-platform-reqs
        - run: cp .env.example .env
        - run: php artisan key:generate
        - run: echo "Build completed successfully!"
