name: Laravel Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
      - run: composer install --ignore-platform-reqs --no-scripts
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: npm install
      - run: npm run build
      - run: echo "✅ Laravel build completed successfully!"
