name: Laravel Build and Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
      - run: composer install --ignore-platform-reqs --no-scripts
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: npm install
      - run: npm run build
      - run: echo "✅ Laravel build completed successfully!"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            cd domains/dokterkuklinik.com/public_html
            git pull origin main
            composer install --no-dev --ignore-platform-reqs --optimize-autoloader
            composer dump-autoload --optimize
            php artisan package:discover --ansi
            php artisan filament:upgrade
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan migrate --force
            chmod -R 755 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
            echo "✅ Deployment complete!"
