name: Laravel Build and Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
      - run: composer install --ignore-platform-reqs --no-scripts
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: npm install
      - run: npm run build
      - run: echo "✅ Laravel build completed successfully!"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            cd domains/dokterkuklinik.com/public_html
            echo "🔧 Starting deployment..."
            git pull origin main
            echo "🚨 Running EMERGENCY DIAGNOSTIC..."
            chmod +x emergency-diagnostic.sh
            ./emergency-diagnostic.sh
            echo "💥 Running NUCLEAR FILAMENT-SHIELD REMOVAL..."
            chmod +x nuclear-shield-removal.sh
            ./nuclear-shield-removal.sh 2>/dev/null || echo "Shield removal skipped"
            echo "🔬 Running ULTIMATE FORENSIC ANALYSIS & FIX..."
            chmod +x ultimate-forensic-fix.sh
            ./ultimate-forensic-fix.sh 2>/dev/null || echo "Forensic fix skipped"
            echo "🗄️ Running DATABASE STRUCTURE FIX..."
            chmod +x database-structure-fix.sh
            ./database-structure-fix.sh 2>/dev/null || echo "Database fix skipped"
            echo "✅ Deployment complete!"
