name: 🔍 Debug GitHub Secrets

on:
  workflow_dispatch:

env:
  HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
  HOSTINGER_USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
  HOSTINGER_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
  DEPLOY_PATH: ${{ secrets.HOSTINGER_DEPLOY_PATH }}

jobs:
  debug-secrets:
    name: 🔍 Check GitHub Secrets Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug GitHub Secrets
        run: |
          echo "🔍 GitHub Secrets Verification"
          echo "=============================="
          echo ""
          
          # Check each secret
          echo "🔑 HOSTINGER_HOST:"
          if [ -n "${HOSTINGER_HOST}" ]; then
            echo "✅ Set: ${HOSTINGER_HOST}"
          else
            echo "❌ NOT SET or EMPTY"
          fi
          
          echo ""
          echo "🔑 HOSTINGER_USERNAME:"
          if [ -n "${HOSTINGER_USERNAME}" ]; then
            echo "✅ Set: ${HOSTINGER_USERNAME}"
          else
            echo "❌ NOT SET or EMPTY"
          fi
          
          echo ""
          echo "🔑 HOSTINGER_PASSWORD:"
          if [ -n "${HOSTINGER_PASSWORD}" ]; then
            echo "✅ Set: [MASKED] (length: ${#HOSTINGER_PASSWORD})"
          else
            echo "❌ NOT SET or EMPTY"
          fi
          
          echo ""
          echo "🔑 HOSTINGER_DEPLOY_PATH:"
          if [ -n "${DEPLOY_PATH}" ]; then
            echo "✅ Set: ${DEPLOY_PATH}"
          else
            echo "❌ NOT SET or EMPTY"
          fi
          
          echo ""
          echo "📋 Expected Values:"
          echo "-------------------"
          echo "HOSTINGER_HOST should be: 153.92.8.132"
          echo "HOSTINGER_USERNAME should be: u454362045"
          echo "HOSTINGER_PASSWORD should be: LaTahzan@01"
          echo "HOSTINGER_DEPLOY_PATH should be: domains/dokterkuklinik.com/public_html/dokterku"
          
          echo ""
          echo "🔧 To Fix:"
          echo "----------"
          echo "1. Go to your repository Settings"
          echo "2. Click on 'Secrets and variables' → 'Actions'"
          echo "3. Add/Update the missing secrets with the correct values"
          echo ""
          
          # Check if all secrets are set
          MISSING_SECRETS=""
          [ -z "${HOSTINGER_HOST}" ] && MISSING_SECRETS="${MISSING_SECRETS} HOSTINGER_HOST"
          [ -z "${HOSTINGER_USERNAME}" ] && MISSING_SECRETS="${MISSING_SECRETS} HOSTINGER_USERNAME"
          [ -z "${HOSTINGER_PASSWORD}" ] && MISSING_SECRETS="${MISSING_SECRETS} HOSTINGER_PASSWORD"
          [ -z "${DEPLOY_PATH}" ] && MISSING_SECRETS="${MISSING_SECRETS} HOSTINGER_DEPLOY_PATH"
          
          if [ -n "${MISSING_SECRETS}" ]; then
            echo "❌ MISSING SECRETS:${MISSING_SECRETS}"
            echo ""
            echo "⚠️  Cannot proceed with SSH connection until all secrets are configured!"
            exit 1
          else
            echo "✅ All secrets are configured!"
          fi