name: 🚀 Deploy Dokter Stats API Fix to Hostinger

on:
  workflow_dispatch:
    inputs:
      test_endpoint:
        description: 'Test API endpoint after deployment'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      clear_caches:
        description: 'Clear Laravel caches after deployment'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  deploy-dokter-stats-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy Dokter Stats API Fix
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "app/Http/Controllers/Api/DokterStatsController.php,routes/api.php"
          target: "/tmp/dokter-fix/"
          strip_components: 0

      - name: 🔧 Install Dokter Stats Fix
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 300s
          script: |
            set -e
            echo "🚀 Installing Dokter Stats API Fix"
            echo "=================================="
            echo "📅 Started at: $(date)"
            
            cd domains/dokterkuklinik.com/public_html
            
            # Create backup of existing files
            echo "💾 Creating backup..."
            mkdir -p ~/backups/dokter-fix/$(date +%Y%m%d_%H%M%S)
            BACKUP_DIR="~/backups/dokter-fix/$(date +%Y%m%d_%H%M%S)"
            
            # Backup existing files if they exist
            [ -f "routes/api.php" ] && cp routes/api.php "$BACKUP_DIR/api.php.backup" || echo "No existing api.php to backup"
            [ -f "app/Http/Controllers/Api/DokterStatsController.php" ] && cp app/Http/Controllers/Api/DokterStatsController.php "$BACKUP_DIR/DokterStatsController.php.backup" || echo "No existing DokterStatsController.php to backup"
            
            # Create necessary directories
            echo "📂 Creating directories..."
            mkdir -p app/Http/Controllers/Api
            
            # Install new files
            echo "📦 Installing new files..."
            cp /tmp/dokter-fix/app/Http/Controllers/Api/DokterStatsController.php app/Http/Controllers/Api/DokterStatsController.php
            cp /tmp/dokter-fix/routes/api.php routes/api.php
            
            # Set proper permissions
            echo "🔐 Setting permissions..."
            chmod 644 app/Http/Controllers/Api/DokterStatsController.php
            chmod 644 routes/api.php
            
            # Clean up temp files
            rm -rf /tmp/dokter-fix
            
            echo "✅ Files installed successfully"

      - name: 🧹 Clear Laravel Caches
        if: github.event.inputs.clear_caches == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd domains/dokterkuklinik.com/public_html
            
            echo "🧹 Clearing Laravel caches..."
            php artisan config:clear || echo "Config clear skipped"
            php artisan route:clear || echo "Route clear skipped"
            php artisan view:clear || echo "View clear skipped"
            php artisan cache:clear || echo "Cache clear skipped"
            
            echo "🎨 Rebuilding caches..."
            php artisan config:cache || echo "Config cache skipped"
            php artisan route:cache || echo "Route cache skipped"
            
            echo "✅ Cache operations completed"

      - name: 🧪 Test Dokter Stats API Endpoints
        if: github.event.inputs.test_endpoint == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🧪 Testing Dokter Stats API Endpoints"
            echo "===================================="
            
            # Test public endpoint (no auth required)
            echo "📊 Testing public stats endpoint..."
            response=$(curl -s -o /dev/null -w "%{http_code}" https://dokterkuklinik.com/api/public/dokter/stats || echo "000")
            echo "   /api/public/dokter/stats → HTTP $response"
            
            if [ "$response" = "200" ]; then
                echo "✅ Public endpoint working!"
                
                # Test actual response content
                echo "📋 Sample response:"
                curl -s https://dokterkuklinik.com/api/public/dokter/stats | head -c 200
                echo ""
            else
                echo "❌ Public endpoint failed with HTTP $response"
            fi
            
            # Test other potential endpoints
            echo ""
            echo "📊 Testing other endpoints..."
            
            response2=$(curl -s -o /dev/null -w "%{http_code}" https://dokterkuklinik.com/api/dokter/stats || echo "000")
            echo "   /api/dokter/stats → HTTP $response2"
            
            response3=$(curl -s -o /dev/null -w "%{http_code}" https://dokterkuklinik.com/api/api/dokter/stats || echo "000")
            echo "   /api/api/dokter/stats → HTTP $response3"

      - name: 📊 Verify Laravel Routes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd domains/dokterkuklinik.com/public_html
            
            echo "📋 Verifying Laravel routes..."
            php artisan route:list | grep -i dokter | head -5 || echo "No dokter routes found in route:list"
            
            echo ""
            echo "🔍 Checking if DokterStatsController exists..."
            if [ -f "app/Http/Controllers/Api/DokterStatsController.php" ]; then
                echo "✅ DokterStatsController.php exists"
                echo "   File size: $(stat -f%z app/Http/Controllers/Api/DokterStatsController.php 2>/dev/null || stat -c%s app/Http/Controllers/Api/DokterStatsController.php) bytes"
            else
                echo "❌ DokterStatsController.php missing"
            fi

      - name: 📋 Deployment Summary
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ""
            echo "📊 DOKTER STATS API FIX DEPLOYMENT SUMMARY"
            echo "=========================================="
            echo "🎯 Objective: Fix 500 error on dokter dashboard stats"
            echo "📅 Deployed: $(date)"
            echo "🔧 Components:"
            echo "   - DokterStatsController.php (New API controller)"
            echo "   - Updated routes/api.php with new endpoints"
            echo ""
            echo "📋 Available Endpoints:"
            echo "   - GET /api/public/dokter/stats (No auth)"
            echo "   - GET /api/dokter/stats (Auth required)"  
            echo "   - GET /api/api/dokter/stats (Auth required)"
            echo ""
            echo "🧪 Test URL:"
            echo "   https://dokterkuklinik.com/api/public/dokter/stats"
            echo ""
            echo "🎯 Expected Result:"
            echo "   - No more 500 errors"
            echo "   - Stats object with proper data structure"
            echo "   - attendance_rate_raw and performance_data defined"
            echo ""
            echo "✅ Deployment Status: ${{ job.status }}"
            echo "🤖 Generated with [ai Code](https://ai.ai/code)"