name: Deploy to Staging

on:
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PHP_VERSION: "8.3"
  NODE_VERSION: "20"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-staging-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-staging-

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-progress --no-interaction

      - name: Setup test environment
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite

      - name: Run tests with coverage
        run: |
          php artisan config:clear
          php artisan migrate --force --database=sqlite
          php artisan db:seed --force --database=sqlite
          # Run tests if they exist
          # vendor/bin/phpunit --coverage-text
          # php artisan test --coverage

      - name: Code quality checks
        run: |
          # Add code quality tools if available
          # vendor/bin/phpstan analyse
          # vendor/bin/php-cs-fixer fix --dry-run --diff
          echo "Code quality checks would run here"

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.dokterkuklinik.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets for staging
        run: npm run build

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          timeout: 300s
          script: |
            set -e
            
            echo "🚀 Starting staging deployment..."
            
            APP_DIR="domains/staging.dokterkuklinik.com/public_html"
            
            cd "$APP_DIR" || { echo "❌ Cannot access staging directory"; exit 1; }
            
            echo "📥 Pulling latest changes..."
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            
            echo "📦 Installing dependencies..."
            composer install --optimize-autoloader --no-interaction
            
            echo "🔧 Setting up staging environment..."
            if [ ! -f .env ]; then
                cp .env.staging .env
            fi
            
            echo "🗄️ Running database operations..."
            php artisan migrate --force
            php artisan db:seed --force --class=TestDataSeeder
            
            echo "🧹 Optimizing for staging..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            echo "🔐 Setting permissions..."
            find storage -type f -exec chmod 644 {} \;
            find storage -type d -exec chmod 755 {} \;
            find bootstrap/cache -type f -exec chmod 644 {} \;
            find bootstrap/cache -type d -exec chmod 755 {} \;
            
            echo "✅ Staging deployment completed!"

      - name: Run staging tests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            cd domains/staging.dokterkuklinik.com/public_html
            
            echo "🧪 Running staging health checks..."
            
            # Check if application is responding
            response=$(curl -s -o /dev/null -w "%{http_code}" https://staging.dokterkuklinik.com || echo "000")
            
            if [ "$response" = "200" ]; then
                echo "✅ Staging application is responding correctly"
            else
                echo "❌ Staging application returned HTTP $response"
                exit 1
            fi
            
            # Run additional staging-specific tests
            # php artisan test --env=staging
            
            echo "✅ All staging tests passed!"

      - name: Comment PR with staging URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Staging deployment completed!**\n\n📍 **Staging URL:** https://staging.dokterkuklinik.com\n\n✅ Ready for testing and review.'
            })