- name: Deploy via SSH
  uses: appleboy/ssh-action@v0.1.5
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: ${{ secrets.SSH_PORT }}
    debug: true
    script: |
      cd domains/dokterkuklinik.com/public_html/dokterku
      git pull origin main
      composer install --no-dev --ignore-platform-reqs
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      echo "✅ Deployment complete!"
