name: Auto Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🚀 Deploy to Hostinger
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 153.92.8.132
        username: u454362045
        password: ${{ secrets.SSH_PASSWORD }}
        port: 65002
        script: |
          cd domains/dokterkuklinik.com/public_html
          echo "🔄 Pulling latest code..."
          git pull origin main
          echo "🗄️ Running migrations..."
          php artisan migrate:status
          echo "🔄 Running new migrations only..."
          php artisan migrate --force 2>/dev/null || echo "⚠️ Some migrations skipped (already exist)"
          echo "🧹 Clearing caches..."
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          echo "⚡ Optimizing..."
          php artisan optimize
          echo "✅ Deployment completed!"