name: Direct Cleanup

on:
  workflow_dispatch:

jobs:
  direct-cleanup:
    name: Direct Server Cleanup
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute direct cleanup and user creation
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🧹 Direct disk cleanup and user creation..."
            
            cd /home/u454362045/domains/dokterkuklinik.com/public_html
            
            echo "📋 1. Check current disk usage:"
            df -h | head -5
            
            echo "📋 2. Clean Laravel cache and temp files:"
            rm -rf storage/framework/cache/data/* 2>/dev/null || echo "Cache already clean"
            rm -rf storage/framework/sessions/* 2>/dev/null || echo "Sessions already clean"  
            rm -rf storage/framework/views/* 2>/dev/null || echo "Views already clean"
            rm -rf storage/logs/*.log 2>/dev/null || echo "Logs already clean"
            
            echo "📋 3. Check disk space after cleanup:"
            df -h | head -5
            
            echo "📋 4. Create admin user directly:"
            mysql -h "127.0.0.1" -u "u454362045_u45436245_kli" -p"LaTahzan@01" -e "
            USE u454362045_u45436245_kli;
            INSERT IGNORE INTO users (name, email, password, created_at, updated_at) 
            VALUES ('Admin', 'admin@admin.com', '\$2y\$12\$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NOW(), NOW());
            " 2>&1
            
            echo "📋 5. Verify user creation:"
            mysql -h "127.0.0.1" -u "u454362045_u45436245_kli" -p"LaTahzan@01" -e "
            USE u454362045_u45436245_kli; 
            SELECT COUNT(*) as total_users FROM users;
            SELECT id, name, email FROM users;
            " 2>/dev/null
            
            echo "📋 6. Clear Laravel caches:"
            php artisan config:clear 2>/dev/null
            php artisan cache:clear 2>/dev/null
            
            echo "📋 7. Test login:"
            curl -X POST \
                 -H "Accept: application/json" \
                 -H "Content-Type: application/json" \
                 -d '{"login":"admin@admin.com","password":"secret","device_id":"test"}' \
                 -w "\nHTTP Status: %{http_code}\n" \
                 -s https://dokterkuklinik.com/api/v2/auth/login
            
            echo "🎉 Direct cleanup complete!"