name: Fix Missing .env File

on:
  workflow_dispatch:

jobs:
  fix-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔧 Fix Missing .env File
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔧 FIXING MISSING .ENV FILE"
            echo "============================"
            
            cd ~/public_html
            
            echo "📁 Current directory contents:"
            ls -la
            echo ""
            
            echo "🔍 Checking for .env files:"
            ls -la | grep env || echo "No .env files found"
            echo ""
            
            if [ -f ".env.production" ]; then
                echo "✅ Found .env.production file"
                echo "📋 Copying .env.production to .env..."
                cp .env.production .env
                echo "✅ .env file created from .env.production"
                
                # Set proper permissions
                chmod 644 .env
                echo "✅ .env permissions set to 644"
                
                echo ""
                echo "📄 .env file contents (first 10 lines):"
                head -10 .env
                echo ""
                
            else
                echo "❌ .env.production not found"
                echo "📝 Creating basic .env file..."
                
                cat > .env << 'EOF'
APP_NAME="Dokterku"
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_TIMEZONE=Asia/Jakarta
APP_URL=https://dokterkuklinik.com

APP_LOCALE=id
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=id_ID

APP_MAINTENANCE_DRIVER=file
APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=u454362045_u45436245_kli
DB_USERNAME=u454362045_u45436245_kli
DB_PASSWORD=KlinikApp2025!

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"
EOF
                
                echo "✅ Basic .env file created"
                chmod 644 .env
                echo "✅ .env permissions set"
            fi
            
            echo ""
            echo "🔑 Generating Laravel application key..."
            php artisan key:generate --force
            echo "✅ Application key generated"
            
            echo ""
            echo "🔍 Verifying Laravel can load..."
            php artisan about --only=environment
            
            echo ""
            echo "🗄️ Running database migrations..."
            php artisan migrate --force
            echo "✅ Database migrations completed"
            
            echo ""
            echo "⚡ Optimizing Laravel..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            echo "✅ Laravel optimized"
            
            echo ""
            echo "🧪 Testing Laravel..."
            if [ -f "artisan" ]; then
                echo "✅ Laravel artisan available"
                php artisan --version
            else
                echo "❌ Laravel artisan not found"
            fi
            
            echo ""
            echo "📁 Final directory check:"
            ls -la
            echo ""
            
            echo "🎉 .ENV FIX COMPLETED!"
            echo "====================="
            echo "🌐 Test website: https://dokterkuklinik.com"
            echo "🔧 Admin panel: https://dokterkuklinik.com/admin"
            echo ""
            echo "If still having issues, check Laravel logs:"
            echo "tail -f storage/logs/laravel.log"