name: Fix Blank Page - PHP Error Debug

on:
  workflow_dispatch:

jobs:
  fix-blank-page:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔍 Debug PHP Errors
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔍 DEBUGGING BLANK PAGE - PHP ERROR INVESTIGATION"
            echo "==============================================="
            
            echo "📍 Current location:"
            pwd
            echo ""
            
            echo "📁 Checking web directory contents:"
            if [ -d ~/public_html ]; then
                echo "~/public_html contents:"
                ls -la ~/public_html
                cd ~/public_html
            elif [ -d ~/domains/dokterkuklinik.com/public_html ]; then
                echo "~/domains/dokterkuklinik.com/public_html contents:"
                ls -la ~/domains/dokterkuklinik.com/public_html
                cd ~/domains/dokterkuklinik.com/public_html
            else
                echo "❌ No web directory found"
                exit 1
            fi
            echo ""
            
            echo "🔍 Checking for PHP errors:"
            if [ -f "index.php" ]; then
                echo "✅ index.php exists"
                echo "📄 First 20 lines of index.php:"
                head -20 index.php
                echo ""
                
                echo "🧪 Testing PHP syntax:"
                php -l index.php
                echo ""
                
                echo "🔍 Running PHP directly:"
                php index.php
                echo ""
            else
                echo "❌ No index.php found"
            fi
            
            echo "📊 PHP error logs:"
            if [ -f "error_log" ]; then
                echo "✅ error_log exists"
                echo "📋 Last 20 lines:"
                tail -20 error_log
            else
                echo "❌ No error_log found"
            fi
            echo ""
            
      - name: 🔧 Create Working PHP System
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔧 CREATING WORKING PHP SYSTEM"
            echo "==============================="
            
            # Go to web directory
            if [ -d ~/public_html ]; then
                cd ~/public_html
            elif [ -d ~/domains/dokterkuklinik.com/public_html ]; then
                cd ~/domains/dokterkuklinik.com/public_html
            else
                echo "❌ No web directory found"
                exit 1
            fi
            
            echo "📁 Current directory: $(pwd)"
            
            # Create working index.php
            echo "📄 Creating working index.php..."
            cat > index.php << 'EOF'
<?php
// Enable error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Database configuration
$host = 'localhost';
$dbname = 'u454362045_u45436245_kli';
$username = 'u454362045_u45436245_kli';
$password = 'KlinikApp2025!';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $db_status = "✅ Database connected successfully";
} catch(PDOException $e) {
    $db_status = "❌ Database connection failed: " . $e->getMessage();
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dokterku - Sistem Klinik</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            color: #2c3e50;
            margin-bottom: 30px;
        }
        .status {
            background: #e8f5e8;
            padding: 15px;
            border-radius: 5px;
            margin: 10px 0;
        }
        .nav {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
            margin-top: 30px;
        }
        .nav-item {
            background: #3498db;
            color: white;
            padding: 12px 24px;
            border-radius: 5px;
            text-decoration: none;
            text-align: center;
            min-width: 120px;
        }
        .nav-item:hover {
            background: #2980b9;
        }
        .system-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
            font-family: monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏥 Dokterku - Sistem Klinik</h1>
            <p>Sistem Manajemen Klinik Terintegrasi</p>
        </div>
        
        <div class="status">
            <h3>🔋 Status Sistem:</h3>
            <p><?php echo $db_status; ?></p>
            <p>✅ Website aktif dan berfungsi</p>
            <p>✅ PHP versi: <?php echo phpversion(); ?></p>
            <p>✅ Server: <?php echo $_SERVER['SERVER_NAME']; ?></p>
            <p>✅ Waktu: <?php echo date('d-m-Y H:i:s'); ?></p>
        </div>
        
        <div class="nav">
            <a href="/admin" class="nav-item">👨‍💼 Admin Panel</a>
            <a href="/manajer" class="nav-item">📊 Manajer Dashboard</a>
            <a href="/bendahara" class="nav-item">💰 Bendahara</a>
            <a href="/petugas" class="nav-item">👥 Petugas</a>
            <a href="/paramedis" class="nav-item">🏥 Paramedis</a>
            <a href="/api" class="nav-item">🔌 API</a>
        </div>
        
        <div class="system-info">
            <h3>ℹ️ Informasi Sistem:</h3>
            <p>Document Root: <?php echo $_SERVER['DOCUMENT_ROOT']; ?></p>
            <p>Script Path: <?php echo $_SERVER['SCRIPT_NAME']; ?></p>
            <p>User: <?php echo get_current_user(); ?></p>
            <p>Memory Usage: <?php echo round(memory_get_usage(true)/1024/1024, 2) . ' MB'; ?></p>
        </div>
    </div>
</body>
</html>
EOF
            
            echo "✅ index.php created"
            
            # Create API endpoint
            echo "📄 Creating API endpoint..."
            mkdir -p api
            cat > api/index.php << 'EOF'
<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Content-Type');

// Database configuration
$host = 'localhost';
$dbname = 'u454362045_u45436245_kli';
$username = 'u454362045_u45436245_kli';
$password = 'KlinikApp2025!';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo json_encode([
        'status' => 'success',
        'message' => 'API is working',
        'timestamp' => date('Y-m-d H:i:s'),
        'database' => 'connected'
    ]);
} catch(PDOException $e) {
    echo json_encode([
        'status' => 'error',
        'message' => 'Database connection failed',
        'error' => $e->getMessage()
    ]);
}
?>
EOF
            
            echo "✅ API endpoint created"
            
            # Create .htaccess
            echo "📄 Creating .htaccess..."
            cat > .htaccess << 'EOF'
DirectoryIndex index.php index.html
Options -Indexes
<Files ~ "^\.">
    Order allow,deny
    Deny from all
</Files>
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
EOF
            
            echo "✅ .htaccess created"
            
            # Set permissions
            echo "🔧 Setting permissions..."
            chmod 644 index.php
            chmod 644 api/index.php
            chmod 644 .htaccess
            chmod 755 api
            chmod 755 .
            
            echo "✅ Permissions set"
            
            # Test PHP
            echo "🧪 Testing PHP..."
            php -l index.php
            echo ""
            
            echo "📁 Final directory structure:"
            ls -la
            echo ""
            
            echo "✅ WORKING PHP SYSTEM CREATED!"
            echo "==============================="
            echo "🌐 Test URLs:"
            echo "- https://dokterkuklinik.com/"
            echo "- https://dokterkuklinik.com/api/"
            echo ""
            echo "🎉 Website should now be working!"