name: Fix ENV Syntax Error

on:
  workflow_dispatch:

jobs:
  fix-env:
    name: Fix .env Syntax
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Upload fix script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "scripts/fix-env-syntax.sh"
          target: "/home/u454362045/"
          
      - name: Fix .env syntax error
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x /home/u454362045/scripts/fix-env-syntax.sh
            bash /home/u454362045/scripts/fix-env-syntax.sh