name: Hostinger Disk Cleanup

on:
  workflow_dispatch:

jobs:
  hostinger-cleanup:
    name: Hostinger Disk Cleanup
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute comprehensive disk cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🧹 Hostinger Disk Space Cleanup..."
            
            cd /home/u454362045
            
            echo "📋 1. Current disk usage:"
            du -sh * 2>/dev/null | sort -hr | head -10
            
            echo ""
            echo "📋 2. Laravel application cleanup:"
            cd /home/u454362045/domains/dokterkuklinik.com/public_html
            
            echo "Cleaning Laravel cache and logs..."
            rm -rf storage/framework/cache/data/* 2>/dev/null && echo "✅ Cache data cleared"
            rm -rf storage/framework/sessions/* 2>/dev/null && echo "✅ Sessions cleared"
            rm -rf storage/framework/views/* 2>/dev/null && echo "✅ Compiled views cleared"
            rm -rf storage/logs/*.log 2>/dev/null && echo "✅ Laravel logs cleared"
            
            echo ""
            echo "📋 3. Remove old backup files:"
            find . -name "*.backup*" -type f -delete 2>/dev/null && echo "✅ Backup files removed"
            rm -f .env.backup.* 2>/dev/null && echo "✅ Old .env backups removed"
            
            echo ""
            echo "📋 4. Clean up migration files:"
            cd database/migrations
            rm -f backup_migrations.sh 2>/dev/null
            rm -f test_migrations.sh 2>/dev/null
            rm -rf merged_originals/ 2>/dev/null && echo "✅ Merged originals removed"
            rm -rf old_migrations/ 2>/dev/null && echo "✅ Old migrations removed"
            rm -rf examples/ 2>/dev/null && echo "✅ Example migrations removed"
            rm -f *.md 2>/dev/null && echo "✅ Documentation files removed"
            rm -f *.json 2>/dev/null && echo "✅ JSON files removed"
            
            echo ""
            echo "📋 5. Clean up large directories:"
            cd /home/u454362045/domains/dokterkuklinik.com/public_html
            rm -rf node_modules/ 2>/dev/null && echo "✅ node_modules removed"
            rm -rf archive/ 2>/dev/null && echo "✅ Archive directory removed"
            rm -rf react-native-backup/ 2>/dev/null && echo "✅ React Native backup removed"
            
            echo ""
            echo "📋 6. Remove test and debug files:"
            rm -f debug-login.php 2>/dev/null
            rm -f test-*.php 2>/dev/null
            rm -f test-*.js 2>/dev/null
            rm -f test-*.mjs 2>/dev/null
            rm -f unregister-sw.html 2>/dev/null
            echo "✅ Test and debug files removed"
            
            echo ""
            echo "📋 7. Clean up temp files:"
            find . -name "*.tmp" -type f -delete 2>/dev/null
            find . -name "*.temp" -type f -delete 2>/dev/null
            find . -name "*.cache" -type f -delete 2>/dev/null
            echo "✅ Temporary files removed"
            
            echo ""
            echo "📋 8. Clean user home directory scripts:"
            cd /home/u454362045
            rm -rf scripts/ 2>/dev/null && echo "✅ Scripts directory removed"
            rm -f *.sh 2>/dev/null && echo "✅ Shell scripts removed"
            
            echo ""
            echo "📋 9. Final disk usage check:"
            cd /home/u454362045
            echo "User directory size:"
            du -sh * 2>/dev/null | sort -hr | head -5
            
            echo ""
            echo "Laravel app size:"
            cd /home/u454362045/domains/dokterkuklinik.com/public_html
            du -sh . 2>/dev/null
            
            echo ""
            echo "Overall disk usage:"
            df -h | head -5
            
            echo ""
            echo "📋 10. Clear Laravel caches after cleanup:"
            php artisan config:clear 2>/dev/null && echo "✅ Config cache cleared"
            php artisan cache:clear 2>/dev/null && echo "✅ Application cache cleared"
            
            echo ""
            echo "🎉 Comprehensive disk cleanup complete!"