name: Investigate 500 Error

on:
  workflow_dispatch:

jobs:
  investigate:
    name: Investigate Persistent 500 Error
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Upload investigation script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "scripts/investigate-500-error.sh"
          target: "/home/u454362045/"
          
      - name: Execute investigation
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x /home/u454362045/scripts/investigate-500-error.sh
            bash /home/u454362045/scripts/investigate-500-error.sh