name: Laravel CI
  on:
    push:
      branches: ["main"]
  jobs:
    test-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
          with:
            php-version: "8.2"

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20.x"
            cache: "npm"

        - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.example', '.env');"

        - name: Install PHP Dependencies
          run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
  --ignore-platform-reqs

        - name: Generate key
          run: php artisan key:generate

        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Install and Build Frontend Dependencies
          run: |
            npm install
            npm run build --if-present

        - name: Basic Check
          run: php artisan route:list --compact

        - name: Deployment Ready
          run: echo "✅ Laravel application is ready for deployment!"
