name: 🚀 Quick Test Migration

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test migration'
        required: true
        default: 'dry-run'
        type: choice
        options:
          - dry-run
          - pending-check
          - single-migration
          - test-rollback
      migration_file:
        description: 'Specific migration file (for single-migration only)'
        required: false
        type: string
      verbose:
        description: 'Enable verbose output'
        required: false
        default: false
        type: boolean

env:
  HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
  HOSTINGER_USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
  HOSTINGER_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
  DEPLOY_PATH: ${{ secrets.HOSTINGER_DEPLOY_PATH }}

jobs:
  quick-test-migrate:
    name: 🧪 Quick Test Migration
    runs-on: ubuntu-latest
    
    steps:
      - name: Install sshpass
        run: |
          echo "🔧 Installing sshpass..."
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Check server connection
        run: |
          echo "🔍 Testing connection to Hostinger..."
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 -o ConnectTimeout=10 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "echo 'Connection successful!' && cd ${DEPLOY_PATH} && pwd"

      - name: Check current migration status
        run: |
          echo "📊 Current migration status:"
          echo "============================"
          
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate:status"

      - name: Dry Run Test
        if: github.event.inputs.test_type == 'dry-run'
        run: |
          echo "🧪 Running migration dry-run test..."
          echo "===================================="
          
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate --pretend"
          
          echo ""
          echo "✅ Dry-run completed - No actual changes made"

      - name: Check Pending Migrations
        if: github.event.inputs.test_type == 'pending-check'
        run: |
          echo "🔍 Checking for pending migrations..."
          echo "====================================="
          
          PENDING=$(sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate:status | grep -c 'Pending' || true")
          
          if [ "$PENDING" -gt 0 ]; then
            echo "⚠️  Found $PENDING pending migration(s)"
            echo ""
            echo "Pending migrations:"
            sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
              "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
              "cd ${DEPLOY_PATH} && php artisan migrate:status | grep 'Pending'"
          else
            echo "✅ No pending migrations found"
          fi

      - name: Test Single Migration
        if: github.event.inputs.test_type == 'single-migration' && github.event.inputs.migration_file != ''
        run: |
          echo "🧪 Testing single migration: ${{ github.event.inputs.migration_file }}"
          echo "========================================================"
          
          # First check if migration exists
          echo "Checking if migration file exists..."
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && ls -la database/migrations/*${{ github.event.inputs.migration_file }}*" || {
              echo "❌ Migration file not found!"
              exit 1
            }
          
          # Show what the migration would do
          echo ""
          echo "Migration preview (--pretend):"
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate --path=database/migrations/*${{ github.event.inputs.migration_file }}* --pretend"
          
          echo ""
          echo "✅ Single migration test completed (dry-run mode)"

      - name: Test Rollback Simulation
        if: github.event.inputs.test_type == 'test-rollback'
        run: |
          echo "🧪 Testing rollback simulation..."
          echo "================================="
          
          # Show last batch info
          echo "Last migration batch info:"
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate:status | tail -10"
          
          # Simulate rollback
          echo ""
          echo "Rollback preview (--pretend):"
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan migrate:rollback --pretend"
          
          echo ""
          echo "✅ Rollback test completed (no actual rollback performed)"

      - name: Verbose Database Info
        if: github.event.inputs.verbose == 'true'
        run: |
          echo "📊 Verbose Database Information"
          echo "==============================="
          
          echo "Database tables:"
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan db:show"
          
          echo ""
          echo "Migration table contents (last 10):"
          sshpass -p "${HOSTINGER_PASSWORD}" ssh -p 65002 \
            "${HOSTINGER_USERNAME}@${HOSTINGER_HOST}" \
            "cd ${DEPLOY_PATH} && php artisan tinker --execute=\"\\DB::table('migrations')->orderBy('id', 'desc')->limit(10)->get()->each(function(\\\$m) { echo \\\$m->migration . ' (Batch: ' . \\\$m->batch . ')' . PHP_EOL; });\""

      - name: Test Summary
        if: always()
        run: |
          echo "🧪 Quick Test Migration Summary"
          echo "==============================="
          echo "✅ Server: ${HOSTINGER_HOST}"
          echo "✅ Path: ${DEPLOY_PATH}"
          echo "✅ Test Type: ${{ github.event.inputs.test_type }}"
          echo "✅ Timestamp: $(date)"
          echo ""
          echo "💡 This was a TEST run - no actual migrations were executed"
          echo "🔒 All operations were performed in read-only or pretend mode"
          echo ""
          echo "📝 Next steps:"
          echo "   - Review the output above"
          echo "   - If everything looks good, run the actual migration workflow"
          echo "   - Use 'hostinger-migrate.yml' for real migrations"