name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      backup_date:
        description: 'Backup date (YYYYMMDD_HHMMSS) or leave empty for latest'
        required: false
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            
            echo "🔄 Starting rollback process..."
            
            APP_DIR="domains/dokterkuklinik.com/public_html/dokterku"
            BACKUP_DATE="${{ github.event.inputs.backup_date }}"
            
            cd "$APP_DIR"
            
            if [ -z "$BACKUP_DATE" ]; then
                # Find the latest backup
                BACKUP_DIR=$(find /tmp -name "dokterku-backup-*" -type d | sort -r | head -1)
                if [ -z "$BACKUP_DIR" ]; then
                    echo "❌ No backup found!"
                    exit 1
                fi
            else
                BACKUP_DIR="/tmp/dokterku-backup-$BACKUP_DATE"
                if [ ! -d "$BACKUP_DIR" ]; then
                    echo "❌ Backup not found: $BACKUP_DIR"
                    exit 1
                fi
            fi
            
            echo "📦 Rolling back from: $BACKUP_DIR"
            
            # Create a backup of current state before rollback
            CURRENT_BACKUP="/tmp/dokterku-pre-rollback-$(date +%Y%m%d_%H%M%S)"
            mkdir -p "$CURRENT_BACKUP"
            rsync -av --exclude='.git' --exclude='node_modules' --exclude='vendor' . "$CURRENT_BACKUP/"
            
            # Perform rollback
            rsync -av --exclude='.env' --exclude='storage/app' --exclude='storage/logs' "$BACKUP_DIR/" .
            
            # Reinstall dependencies
            composer install --no-dev --optimize-autoloader --no-interaction
            
            # Run necessary Laravel commands
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            echo "✅ Rollback completed successfully!"
            echo "📦 Current state backed up to: $CURRENT_BACKUP"
            echo "🔄 Rolled back from: $BACKUP_DIR"

      - name: Verify rollback
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🔍 Verifying rollback..."
            
            response=$(curl -s -o /dev/null -w "%{http_code}" https://dokterkuklinik.com || echo "000")
            
            if [ "$response" = "200" ]; then
                echo "✅ Application is responding correctly after rollback (HTTP $response)"
            else
                echo "❌ Application is not responding correctly (HTTP $response)"
                echo "🔍 Checking logs..."
                tail -20 domains/dokterkuklinik.com/public_html/dokterku/storage/logs/laravel.log || echo "No logs found"
            fi