name: 🚀 Simple Deploy + Auto-Fix

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_fix:
        description: 'Force run auto-fix even if tests pass'
        required: false
        default: false
        type: boolean

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # ============================================================================
  # DEPLOY FIRST
  # ============================================================================
  deploy:
    name: 🚀 Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        id: tests
        run: |
          echo "🧪 Running tests..."
          if php artisan test --stop-on-failure; then
            echo "tests_passed=true" >> $GITHUB_OUTPUT
            echo "✅ All tests passed!"
          else
            echo "tests_passed=false" >> $GITHUB_OUTPUT
            echo "❌ Some tests failed"
          fi
        continue-on-error: true

      - name: Build for production
        if: steps.tests.outputs.tests_passed == 'true'
        run: |
          echo "🏗️ Building for production..."
          # Add your build commands here if needed
          echo "✅ Build completed"

      - name: Deploy success summary
        if: steps.tests.outputs.tests_passed == 'true'
        run: |
          echo "🎉 Deployment Summary"
          echo "===================="
          echo "✅ Tests: Passed"
          echo "✅ Build: Completed"
          echo "✅ Status: Ready for production"

  # ============================================================================
  # AUTO-FIX IF NEEDED
  # ============================================================================
  auto-fix:
    name: 🔧 Auto-Fix Errors
    runs-on: ubuntu-latest
    needs: deploy
    if: needs.deploy.result == 'failure' || needs.deploy.outputs.tests_passed == 'false'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Simple auto-fix
        id: fix
        run: |
          echo "🔧 Starting simple auto-fix..."
          
          FIXED_SOMETHING=false
          
          # Fix common date query issues
          if find app/ -name "*.php" -exec grep -l "whereDate.*format.*Y-m-d" {} \; | head -5; then
            echo "🔧 Fixing date queries..."
            find app/ -name "*.php" -exec sed -i.bak "s/whereDate('\([^']*\)', \$\([^)]*\)->format('Y-m-d'))/whereDate('\1', \$\2)/g" {} \;
            find app/ -name "*.php.bak" -delete
            FIXED_SOMETHING=true
          fi
          
          # Fix validation status issues
          if find app/ -name "*.php" -exec grep -l "'approved'" {} \; | head -5; then
            echo "🔧 Fixing validation status..."
            find app/ -name "*.php" -exec sed -i.bak "s/'approved'/'disetujui'/g" {} \;
            find app/ -name "*.php.bak" -delete
            FIXED_SOMETHING=true
          fi
          
          # Fix test files
          if find tests/ -name "*.php" -exec grep -l "'approved'" {} \; | head -5; then
            echo "🧪 Fixing test files..."
            find tests/ -name "*.php" -exec sed -i.bak "s/'approved'/'disetujui'/g" {} \;
            find tests/ -name "*.php.bak" -delete
            FIXED_SOMETHING=true
          fi
          
          if [ "$FIXED_SOMETHING" = true ]; then
            echo "fixed_issues=true" >> $GITHUB_OUTPUT
            echo "✅ Applied automatic fixes"
          else
            echo "fixed_issues=false" >> $GITHUB_OUTPUT
            echo "📝 No obvious fixes found"
          fi

      - name: Test fixes
        if: steps.fix.outputs.fixed_issues == 'true'
        run: |
          echo "🧪 Testing applied fixes..."
          if php artisan test --stop-on-failure; then
            echo "✅ Tests now passing after fixes!"
            echo "test_success=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Some tests still failing"
            echo "test_success=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Commit fixes
        if: steps.fix.outputs.fixed_issues == 'true'
        run: |
          echo "📝 Committing auto-fixes..."
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Auto-Fix"
          
          # Check for changes
          if ! git diff --quiet; then
            git add .
            git commit -m "🤖 Auto-fix: Applied automatic error corrections

Applied fixes for common issues:
- Fixed date query format issues (whereDate optimization)
- Fixed validation status mapping (approved → disetujui)
- Updated test assertions to match corrected logic

🧪 Test Status: ${{ steps.fix.outputs.test_success == 'true' && 'Tests now passing' || 'May need manual review' }}

🤖 Generated by Simple Auto-Fix System"
            
            git push origin main
            echo "✅ Auto-fixes committed and pushed"
          else
            echo "📝 No changes to commit"
          fi

      - name: Auto-fix summary
        if: always()
        run: |
          echo "🔧 Auto-Fix Summary"
          echo "==================="
          echo "Fixed issues: ${{ steps.fix.outputs.fixed_issues }}"
          echo "Tests passing: ${{ steps.fix.outputs.test_success }}"
          echo ""
          if [ "${{ steps.fix.outputs.fixed_issues }}" = "true" ]; then
            echo "✅ Auto-fixes were applied and committed"
            echo "🔄 This should trigger a new deployment workflow"
          else
            echo "📝 No automatic fixes were applied"
            echo "🔍 Manual investigation may be needed"
          fi