name: 🏆 World-Class Root Analysis - Hostinger vs Local Deep Comparison

on:
  workflow_dispatch:
    inputs:
      analysis_depth:
        description: 'Analysis depth level'
        required: false
        default: 'comprehensive'
        type: choice
        options:
          - 'comprehensive'
          - 'ultra_deep'
          - 'forensic'

jobs:
  world-class-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🔬 Forensic Analysis - Hostinger Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 900s
          script: |
            set -e
            echo "🏆 WORLD-CLASS ROOT ANALYSIS: Dokter Dashboard"
            echo "=============================================="
            echo "📅 Analysis Time: $(date)"
            echo "🎯 Environment: Hostinger Production"
            echo ""
            
            cd domains/dokterkuklinik.com/public_html
            
            # ===============================================
            # 1. CRITICAL FILE EXISTENCE & INTEGRITY CHECK
            # ===============================================
            echo "🔍 SECTION 1: Critical File Integrity Analysis"
            echo "----------------------------------------------"
            
            echo "📂 Controller Files:"
            if [ -f "app/Http/Controllers/Api/DokterStatsController.php" ]; then
                echo "✅ DokterStatsController.php EXISTS"
                echo "   Size: $(stat -c%s app/Http/Controllers/Api/DokterStatsController.php) bytes"
                echo "   Modified: $(stat -c%y app/Http/Controllers/Api/DokterStatsController.php)"
                echo "   Permissions: $(stat -c%a app/Http/Controllers/Api/DokterStatsController.php)"
                
                # Check if it has the stats method
                if grep -q "public function stats" app/Http/Controllers/Api/DokterStatsController.php; then
                    echo "✅ stats() method found in controller"
                else
                    echo "❌ stats() method NOT found in controller"
                fi
                
                # Check for syntax errors
                echo "🔍 PHP Syntax Check:"
                php -l app/Http/Controllers/Api/DokterStatsController.php || echo "❌ PHP syntax error in controller"
                
            else
                echo "❌ DokterStatsController.php MISSING"
            fi
            
            echo ""
            echo "📂 Route Files:"
            if [ -f "routes/api.php" ]; then
                echo "✅ routes/api.php EXISTS"
                echo "   Size: $(stat -c%s routes/api.php) bytes"
                echo "   Modified: $(stat -c%y routes/api.php)"
                
                # Check route content
                echo "🔍 Route Analysis:"
                if grep -q "DokterStatsController" routes/api.php; then
                    echo "✅ DokterStatsController routes found"
                    echo "📋 Found routes:"
                    grep -n "DokterStatsController\|/dokter" routes/api.php | head -5
                else
                    echo "❌ DokterStatsController routes NOT found"
                fi
            else
                echo "❌ routes/api.php MISSING"
            fi
            
            # ===============================================
            # 2. LARAVEL ENVIRONMENT DEEP ANALYSIS
            # ===============================================
            echo ""
            echo "🔍 SECTION 2: Laravel Environment Deep Analysis"
            echo "----------------------------------------------"
            
            echo "🔧 Laravel Status:"
            php artisan --version || echo "❌ Laravel artisan not working"
            
            echo ""
            echo "🗂️ Environment Configuration:"
            echo "APP_ENV: $(grep '^APP_ENV=' .env | cut -d'=' -f2)"
            echo "APP_DEBUG: $(grep '^APP_DEBUG=' .env | cut -d'=' -f2)"
            echo "APP_URL: $(grep '^APP_URL=' .env | cut -d'=' -f2)"
            
            echo ""
            echo "📋 Route Cache Status:"
            if [ -f "bootstrap/cache/routes-v7.php" ]; then
                echo "✅ Route cache exists"
                echo "   Size: $(stat -c%s bootstrap/cache/routes-v7.php) bytes"
                echo "   Modified: $(stat -c%y bootstrap/cache/routes-v7.php)"
            else
                echo "❌ Route cache missing"
            fi
            
            echo ""
            echo "🔍 Config Cache Status:"
            if [ -f "bootstrap/cache/config.php" ]; then
                echo "✅ Config cache exists"
                echo "   Size: $(stat -c%s bootstrap/cache/config.php) bytes"
                echo "   Modified: $(stat -c%y bootstrap/cache/config.php)"
            else
                echo "❌ Config cache missing"
            fi
            
            # ===============================================
            # 3. ACTUAL ROUTE REGISTRATION TEST
            # ===============================================
            echo ""
            echo "🔍 SECTION 3: Route Registration Forensics"
            echo "------------------------------------------"
            
            echo "📋 Laravel Route List (Dokter related):"
            php artisan route:list --compact 2>/dev/null | grep -i dokter || echo "❌ No dokter routes found in route:list"
            
            echo ""
            echo "📋 All API Routes:"
            php artisan route:list --compact 2>/dev/null | grep "api/" | head -10 || echo "❌ No API routes found"
            
            # ===============================================
            # 4. DIRECT CONTROLLER INSTANTIATION TEST
            # ===============================================
            echo ""
            echo "🔍 SECTION 4: Controller Instantiation Test"
            echo "-------------------------------------------"
            
            echo "🧪 Testing controller instantiation:"
            php -r "
            require 'vendor/autoload.php';
            \$app = require_once 'bootstrap/app.php';
            \$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
            
            try {
                \$controller = new App\Http\Controllers\Api\DokterStatsController();
                echo '✅ Controller instantiated successfully\n';
                
                if (method_exists(\$controller, 'stats')) {
                    echo '✅ stats() method exists\n';
                    
                    // Test method call
                    try {
                        \$response = \$controller->stats();
                        echo '✅ stats() method callable\n';
                        echo 'Response type: ' . get_class(\$response) . \"\n\";
                    } catch (Exception \$e) {
                        echo '❌ stats() method call failed: ' . \$e->getMessage() . \"\n\";
                    }
                } else {
                    echo '❌ stats() method does not exist\n';
                }
            } catch (Exception \$e) {
                echo '❌ Controller instantiation failed: ' . \$e->getMessage() . \"\n\";
            }
            " || echo "❌ Controller test script failed"
            
            # ===============================================
            # 5. WEB SERVER & PHP ANALYSIS
            # ===============================================
            echo ""
            echo "🔍 SECTION 5: Web Server & PHP Environment"
            echo "------------------------------------------"
            
            echo "🔧 PHP Configuration:"
            php -r "echo 'PHP Version: ' . PHP_VERSION . \"\n\";"
            php -r "echo 'Memory Limit: ' . ini_get('memory_limit') . \"\n\";"
            php -r "echo 'Max Execution Time: ' . ini_get('max_execution_time') . \"\n\";"
            php -r "echo 'Error Reporting: ' . error_reporting() . \"\n\";"
            
            echo ""
            echo "📁 Laravel Permissions:"
            echo "storage/ permissions: $(stat -c%a storage/)"
            echo "bootstrap/cache/ permissions: $(stat -c%a bootstrap/cache/)"
            
            # ===============================================
            # 6. ERROR LOG FORENSIC ANALYSIS
            # ===============================================
            echo ""
            echo "🔍 SECTION 6: Error Log Forensic Analysis"
            echo "-----------------------------------------"
            
            echo "📋 Recent Laravel Errors (Last 20 lines):"
            if [ -f "storage/logs/laravel.log" ]; then
                echo "Log file size: $(stat -c%s storage/logs/laravel.log) bytes"
                echo ""
                echo "🔥 Most Recent Errors:"
                tail -50 storage/logs/laravel.log | grep -E "(ERROR|CRITICAL|FATAL)" | tail -10 || echo "No recent errors found"
                
                echo ""
                echo "🩺 Dokter-Related Errors:"
                tail -100 storage/logs/laravel.log | grep -i dokter | tail -5 || echo "No dokter-related errors found"
                
                echo ""
                echo "🔍 500 Error Traces:"
                tail -100 storage/logs/laravel.log | grep -A 5 -B 5 "500\|Internal Server Error" | tail -20 || echo "No 500 error traces found"
            else
                echo "❌ Laravel log file not found"
            fi
            
            # ===============================================
            # 7. DIRECT HTTP TEST VIA INTERNAL CURL
            # ===============================================
            echo ""
            echo "🔍 SECTION 7: Internal HTTP Testing"
            echo "-----------------------------------"
            
            echo "🌐 Testing endpoints from server:"
            
            # Test different endpoint variations
            endpoints=(
                "http://localhost/api/dokter/stats"
                "http://localhost/dokter/stats" 
                "http://localhost/dokter"
                "http://localhost/api/public/dokter/stats"
            )
            
            for endpoint in "${endpoints[@]}"; do
                echo "Testing: $endpoint"
                response=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint" 2>/dev/null || echo "000")
                echo "   Response: HTTP $response"
                
                if [ "$response" = "200" ]; then
                    echo "   ✅ SUCCESS - Testing response content:"
                    curl -s "$endpoint" | head -c 100 || echo "   Failed to get content"
                elif [ "$response" = "500" ]; then
                    echo "   ❌ 500 ERROR - This is our problem!"
                fi
            done
            
            # ===============================================
            # 8. COMPOSER & AUTOLOAD ANALYSIS
            # ===============================================
            echo ""
            echo "🔍 SECTION 8: Composer & Autoload Analysis"
            echo "------------------------------------------"
            
            echo "📦 Composer Status:"
            if [ -f "composer.json" ]; then
                echo "✅ composer.json exists"
                echo "Laravel version: $(grep '"laravel/framework"' composer.json | head -1)"
            fi
            
            if [ -f "vendor/autoload.php" ]; then
                echo "✅ Composer autoload exists"
                echo "   Size: $(stat -c%s vendor/autoload.php) bytes"
                echo "   Modified: $(stat -c%y vendor/autoload.php)"
            else
                echo "❌ Composer autoload missing - Run composer install!"
            fi
            
            echo ""
            echo "🔍 Class Autoload Test:"
            php -r "
            require 'vendor/autoload.php';
            if (class_exists('App\Http\Controllers\Api\DokterStatsController')) {
                echo '✅ DokterStatsController class can be autoloaded\n';
            } else {
                echo '❌ DokterStatsController class CANNOT be autoloaded\n';
            }
            " || echo "❌ Autoload test failed"
            
            # ===============================================
            # 9. FINAL DIAGNOSIS & RECOMMENDATIONS
            # ===============================================
            echo ""
            echo "🔍 SECTION 9: Root Cause Diagnosis"
            echo "----------------------------------"
            
            echo "🎯 CRITICAL FINDINGS SUMMARY:"
            echo "1. File deployment status"
            echo "2. Laravel environment integrity" 
            echo "3. Route registration success/failure"
            echo "4. Controller instantiation capability"
            echo "5. Autoloading functionality"
            echo "6. Specific error patterns in logs"
            echo ""
            
            echo "📋 NEXT ACTIONS REQUIRED:"
            echo "Based on the above analysis, the root cause will be identified"
            echo "and specific fix recommendations will be provided."
            echo ""
            echo "✅ WORLD-CLASS ANALYSIS COMPLETED"
            echo "Total analysis time: $SECONDS seconds"

      - name: 🧪 Comparative Analysis with Local Environment
        run: |
          echo "🔬 LOCAL ENVIRONMENT ANALYSIS FOR COMPARISON"
          echo "============================================"
          
          # Test local controller
          echo "📂 Local Controller Status:"
          if [ -f "app/Http/Controllers/Api/DokterStatsController.php" ]; then
              echo "✅ Local DokterStatsController.php exists"
              echo "   Size: $(stat -f%z app/Http/Controllers/Api/DokterStatsController.php) bytes"
              
              # Test syntax
              php -l app/Http/Controllers/Api/DokterStatsController.php
          else
              echo "❌ Local DokterStatsController.php missing"
          fi
          
          echo ""
          echo "📂 Local Routes:"
          if [ -f "routes/api.php" ]; then
              echo "✅ Local routes/api.php exists"
              if grep -q "DokterStatsController" routes/api.php; then
                  echo "✅ DokterStatsController routes found in local"
                  echo "📋 Local routes:"
                  grep -n "DokterStatsController\|/dokter" routes/api.php | head -3
              fi
          fi
          
          echo ""
          echo "🔍 Local Laravel Environment:"
          if [ -f "artisan" ]; then
              php artisan --version || echo "Local Laravel not available"
              
              echo "📋 Local Routes Test:"
              php artisan route:list --compact | grep -i dokter || echo "No local dokter routes"
          fi

      - name: 📊 Generate World-Class Recommendations
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ""
            echo "🏆 WORLD-CLASS ANALYSIS SUMMARY & RECOMMENDATIONS"
            echo "=================================================="
            echo "📅 Analysis Completed: $(date)"
            echo "🎯 Status: Comprehensive forensic analysis completed"
            echo ""
            echo "🔍 ROOT CAUSE ANALYSIS FINDINGS:"
            echo "1. File integrity check results"
            echo "2. Laravel environment status"
            echo "3. Route registration analysis"
            echo "4. Controller instantiation tests"
            echo "5. Error log forensics"
            echo "6. HTTP endpoint testing"
            echo ""
            echo "🛠️ WORLD-CLASS SOLUTIONS:"
            echo "Based on analysis results, targeted fixes will be implemented"
            echo ""
            echo "📈 EXPECTED OUTCOME:"
            echo "✅ 500 errors eliminated"
            echo "✅ Stats API functioning correctly"
            echo "✅ undefined values resolved"
            echo "✅ Dashboard fully operational"
            echo ""
            echo "🤖 Generated with [ai Code](https://ai.ai/code)"
            echo "🏆 World-Class Root Analysis Complete"